[tool:pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short --html=reports/report.html --self-contained-html --log-cli-level=INFO --log-cli-format=%(asctime)s %(levelname)s %(message)s --log-cli-date-format=%Y-%m-%d %H:%M:%S --screenshot-on-failure